version: "3"

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: boards_api
      POSTGRES_PASSWORD: boards_api
      POSTGRES_DB: boards_api_development
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app
    ports:
      - 3000:3000

  api-client:
    build: ./client
    command: npm start -- --host 0.0.0.0
    depends_on:
      - api
    links:
      - api
    volumes:
      - ./client:/app
    ports:
      - 4200:4200

volumes:
  db-data:
