# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 88a5f5ccb0df38d5eece91a4fee1044c08b7a6878c47c3a88bff0ec98a949ef6996b37b1730f2ecf3dc210f18fa5d8341f02f41a998a177929792fe25b03790d

test:
  secret_key_base: e72ffa8539fe41def79fcb7ba712c596acee95d2fb9d48a0fbeb8743f4e26db96e3343af1ac77e75e802dbd25b0c71d1b584736f03a53301e773f7576480dd73

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
