require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe Boards::ListsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # List. As you add validations to List, be sure to
  # adjust the attributes here as well.
  let(:board_id) {
    Board.create!(name: 'board').to_param
  }

  let(:valid_attributes) {
    { board_id: board_id, name: 'list', position: 1 }
  }

  let(:invalid_attributes) {
    { board_id: nil, name: nil, position: nil }
  }

  describe "POST #create" do
    context "with valid params" do
      it "creates a new List" do
        expect {
          post :create, params: { board_id: board_id, list: valid_attributes }, format: :json
        }.to change(List, :count).by(1)
      end

      it "renders a JSON response with the new list" do

        post :create, params: { board_id: board_id, list: valid_attributes }, format: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to eq('application/json')
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the new list" do

        post :create, params: { board_id: board_id, list: invalid_attributes }, format: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { name: 'new_list_name', position: 2 }
      }

      it "updates the requested list" do
        list = List.create! valid_attributes
        put :update, params: { board_id: board_id, id: list.to_param, list: new_attributes }, format: :json
        list.reload
        expect(list.name).to eq(new_attributes[:name])
        expect(list.position).to eq(new_attributes[:position])
      end

      it "renders a JSON response with the list" do
        list = List.create! valid_attributes

        put :update, params: { board_id: board_id, id: list.to_param, list: valid_attributes }, format: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq('application/json')
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the list" do
        list = List.create! valid_attributes

        put :update, params: { board_id: board_id, id: list.to_param, list: invalid_attributes }, format: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested list" do
      list = List.create! valid_attributes
      expect {
        delete :destroy, params: { board_id: board_id, id: list.to_param }, format: :json
      }.to change(List, :count).by(-1)
    end
  end

end
