require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe BoardsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Board. As you add validations to Board, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: 'board_name' }
  }

  let(:invalid_attributes) {
    { name: nil }
  }

  describe "GET #index" do
    it "returns a success response" do
      board = Board.create! valid_attributes
      get :index, params: {}, format: :json
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      board = Board.create! valid_attributes
      get :show, params: { id: board.to_param }, format: :json
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Board" do
        expect {
          post :create, params: { board: valid_attributes }, format: :json
        }.to change(Board, :count).by(1)
      end

      it "renders a JSON response with the new board" do
        post :create, params: { board: valid_attributes }, format: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to eq('application/json')
        expect(response.location).to eq(board_url(Board.last))
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the new board" do
        post :create, params: { board: invalid_attributes }, format: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        { name: 'new_board_name' }
      }

      it "updates the requested board" do
        board = Board.create! valid_attributes
        put :update, params: { id: board.to_param, board: new_attributes }, format: :json
        board.reload
        expect(board.name).to eq(new_attributes[:name])
      end

      it "renders a JSON response with the board" do
        board = Board.create! valid_attributes

        put :update, params: { id: board.to_param, board: valid_attributes }, format: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq('application/json')
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the board" do
        board = Board.create! valid_attributes

        put :update, params: { id: board.to_param, board: invalid_attributes }, format: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested board" do
      board = Board.create! valid_attributes
      expect {
        delete :destroy, params: { id: board.to_param }, format: :json
      }.to change(Board, :count).by(-1)
    end
  end

end
